#!/usr/bin/env node
// Build every generated file from tokens/*.json and css/*.css.
//
//   node scripts/build.mjs           write dist/, specimens/index.html, foundations/color-contrast.md
//   node scripts/build.mjs --check   write nothing; fail if any output is stale or any rule is broken
//
// Rules enforced (both modes):
//   - every alias resolves, every zh override has a base token        (DR-003)
//   - every allowed color pairing meets WCAG 2.2 AA                    (DR-011)
//   - no CJK font size below 13px                                      (DR-005)
//   - no literal hex colors in css/, components/, specimens/src/       (spec §5)

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, extname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  readJSON, flatten, resolve, dependents, varName, toCss, hexToRgba, over, contrast, THRESHOLDS,
} from "./lib.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const at = (p) => join(ROOT, p);
const CHECK = process.argv.includes("--check");
const problems = [];

// ---------------------------------------------------------------- load
const base = flatten(readJSON(at("tokens/tokens.json")));
const zhOnly = flatten(readJSON(at("tokens/lang-zh.json")));
const zh = new Map(base);
for (const [path, token] of zhOnly) {
  if (!base.has(path)) problems.push(`lang-zh.json overrides "${path}", which tokens.json does not define`);
  else zh.set(path, { ...base.get(path), ...token, type: token.type ?? base.get(path).type });
}
for (const [label, map] of [["base", base], ["zh", zh]]) {
  for (const path of map.keys()) {
    try { resolve(path, map); } catch (e) { problems.push(`${label}: ${e.message}`); }
  }
}
if (problems.length) fail();

// ---------------------------------------------------------------- tokens.css
const changed = new Set(zhOnly.keys());
const zhSet = new Set([...changed, ...dependents(zh, changed), ...dependents(base, changed)]);
const zhPaths = [...base.keys()].filter((p) => zhSet.has(p));

const block = (selector, paths, map) =>
  `${selector} {\n${paths.map((p) => `  ${varName(p)}: ${toCss(map.get(p))};`).join("\n")}\n}\n`;

const GEN_CSS = "/* Generated by scripts/build.mjs from tokens/*.json. Do not edit. */\n";
const tokensCss =
  GEN_CSS +
  block(":root", [...base.keys()], base) +
  "\n/* Traditional Chinese: DR-005, DR-006, DR-007 */\n" +
  block(":lang(zh)", zhPaths, zh) +
  "\n/* English inside Chinese content gets the base values back */\n" +
  block(":lang(en)", zhPaths, base);

const wwCss = [
  tokensCss,
  readFileSync(at("css/base.css"), "utf8"),
  readFileSync(at("css/type.css"), "utf8"),
].join("\n");

// ---------------------------------------------------------------- tokens.ts
function nest(map, paths) {
  const root = {};
  for (const path of paths) {
    const keys = path.split(".");
    let cur = root;
    for (const k of keys.slice(0, -1)) cur = cur[k] ??= {};
    const t = resolve(path, map);
    cur[keys.at(-1)] = typeof t.value === "number" ? t.value : toCss(t);
  }
  return root;
}
const tokensTs = [
  "// Generated by scripts/build.mjs from tokens/*.json. Do not edit.",
  `export const tokens = ${JSON.stringify(nest(base, [...base.keys()]), null, 2)} as const;`,
  "",
  "/** Values that differ under :lang(zh). */",
  `export const tokensZh = ${JSON.stringify(nest(zh, zhPaths), null, 2)} as const;`,
  "",
  "/** CSS custom property reference for a token path, e.g. cssVar(\"color.text.primary\"). */",
  "export const cssVar = (path: string): string => `var(--ww-${path.replace(/\\./g, \"-\")})`;",
  "",
].join("\n");

// ---------------------------------------------------------------- contrast
const pairs = readJSON(at("tokens/contrast-pairs.json")).pairs;
const pageColor = hexToRgba(resolve("color.background.page", base).value);
const LEVEL_ZH = { text: "文字", large: "大字", ui: "介面元件" };
const rows = [];
for (const pair of pairs) {
  for (const bgPath of pair.bg) {
    const fgHex = resolve(pair.fg, base).value;
    const bgHex = resolve(bgPath, base).value;
    const bg = over(hexToRgba(bgHex), pageColor);
    const fg = over(hexToRgba(fgHex), bg);
    const ratio = contrast(fg, bg);
    const min = THRESHOLDS[pair.level];
    const pass = ratio >= min;
    rows.push({ fg: pair.fg, fgHex, bg: bgPath, bgHex, level: pair.level, ratio, min, pass });
    if (!pass) problems.push(`contrast: ${pair.fg} on ${bgPath} is ${floor2(ratio)}:1, needs ${min}:1`);
  }
}
function floor2(n) { return (Math.floor(n * 100) / 100).toFixed(2); }

const contrastMd = [
  "<!-- Generated by scripts/build.mjs from tokens/contrast-pairs.json. Do not edit. -->",
  "",
  "# 色彩對比表",
  "",
  "系統允許的所有前景與背景組合。門檻依 [DR-011](../decisions/DR-011-accessibility-threshold.md)：文字 4.5:1，大字與介面元件 3:1。",
  "未列在這張表裡的組合不允許使用。對比值無條件捨去到小數第二位。",
  "",
  "| 前景 | 背景 | 類型 | 對比 | 門檻 | 結果 |",
  "|---|---|---|---|---|---|",
  ...rows.map((r) =>
    `| \`${r.fg}\` ${r.fgHex.toUpperCase()} | \`${r.bg}\` ${r.bgHex.toUpperCase()} | ${LEVEL_ZH[r.level]} | ${floor2(r.ratio)}:1 | ${r.min}:1 | ${r.pass ? "通過" : "**未通過**"} |`),
  "",
].join("\n");

// ---------------------------------------------------------------- CJK minimum size
const remMin = (v) => {
  const m = String(v).match(/(-?\d*\.?\d+)rem/);
  return m ? parseFloat(m[1]) : null;
};
for (const path of zh.keys()) {
  if (!path.startsWith("font.size.")) continue;
  const rem = remMin(resolve(path, zh).value);
  if (rem !== null && rem < 0.8125) problems.push(`CJK minimum: ${path} resolves to ${rem}rem under :lang(zh); minimum is 0.8125rem (13px)`);
}

// ---------------------------------------------------------------- specimens
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const palettePaths = [...base.keys()].filter((p) => p.split(".").length === 2 && p.startsWith("color."));
const paletteHtml = palettePaths.map((p) => {
  const t = base.get(p);
  const name = p.split(".")[1];
  return `<figure class="swatch"><div class="chip" style="background: var(${varName(p)})"></div>` +
    `<figcaption><strong>${esc(name)}</strong><code>${esc(t.value.toUpperCase())}</code>` +
    `<span>${esc(t.description ?? "")}</span></figcaption></figure>`;
}).join("\n");

const contrastHtml = `<div class="table-wrap"><table class="contrast"><thead><tr>` +
  `<th>樣本</th><th>前景</th><th>背景</th><th>類型</th><th>對比</th><th>門檻</th></tr></thead><tbody>\n` +
  rows.map((r) =>
    `<tr><td><span class="sample" style="color: var(${varName(r.fg)}); background: var(${varName(r.bg)})">Aa 鯨</span></td>` +
    `<td><code>${esc(r.fg)}</code></td><td><code>${esc(r.bg)}</code></td><td>${LEVEL_ZH[r.level]}</td>` +
    `<td class="num">${floor2(r.ratio)}:1</td><td class="num">${r.min}:1</td></tr>`).join("\n") +
  `\n</tbody></table></div>`;

const typePaths = [...base.keys()].filter((p) => /^(font\.(family|size|weight|style|transform)|line-height|letter-spacing)\./.test(p));
const typeHtml = `<div class="table-wrap"><table class="tokens"><thead><tr><th>Token</th><th>英文與預設</th><th>:lang(zh)</th></tr></thead><tbody>\n` +
  typePaths.map((p) => {
    const en = resolve(p, base); const z = resolve(p, zh);
    const enV = typeof en.value === "number" ? en.value : toCss(en);
    const zhV = typeof z.value === "number" ? z.value : toCss(z);
    return `<tr><td><code>${esc(varName(p))}</code></td><td>${esc(enV)}</td><td${zhV !== enV ? ' class="diff"' : ""}>${zhV !== enV ? esc(zhV) : "同左"}</td></tr>`;
  }).join("\n") + `\n</tbody></table></div>`;

const specimenSrc = readFileSync(at("specimens/src/index.html"), "utf8");
const specimen =
  "<!-- Generated by scripts/build.mjs from specimens/src/index.html. Do not edit. -->\n" +
  specimenSrc
    .replace("<!-- @ww:css -->", () => `<style>\n${wwCss}\n</style>`)
    .replace("<!-- @ww:palette -->", () => paletteHtml)
    .replace("<!-- @ww:contrast -->", () => contrastHtml)
    .replace("<!-- @ww:type-tokens -->", () => typeHtml);

// ---------------------------------------------------------------- literal hex lint
const HEX = /(?<![&\w])#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})\b/g;
function walk(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}
const styleOnly = (html) => [
  ...[...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].map((m) => m[1]),
  ...[...html.matchAll(/style="([^"]*)"/gi)].map((m) => m[1]),
].join("\n");
const knownVars = new Set([...base.keys()].map(varName));
const lintTargets = [...walk(at("css")), ...walk(at("components")), ...walk(at("specimens/src"))];
for (const file of lintTargets) {
  const ext = extname(file);
  if (![".css", ".html"].includes(ext)) continue;
  let text = readFileSync(file, "utf8");
  text = ext === ".html" ? styleOnly(text) : text;
  text = text.replace(/\/\*[\s\S]*?\*\//g, "");
  for (const m of text.matchAll(HEX)) problems.push(`literal hex ${m[0]} in ${relative(ROOT, file)}; use a token`);
  for (const m of text.matchAll(/var\((--ww-[a-z0-9-]+)/g)) {
    if (!knownVars.has(m[1])) problems.push(`unknown token ${m[1]} in ${relative(ROOT, file)}`);
  }
}

// ---------------------------------------------------------------- write or verify
const outputs = {
  "dist/tokens.css": tokensCss,
  "dist/ww.css": wwCss,
  "dist/tokens.ts": tokensTs,
  "foundations/color-contrast.md": contrastMd,
  "specimens/index.html": specimen,
};
for (const [path, content] of Object.entries(outputs)) {
  const full = at(path);
  if (CHECK) {
    const current = existsSync(full) ? readFileSync(full, "utf8") : null;
    if (current !== content) problems.push(`${path} is stale; run npm run build and commit the result`);
  } else {
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content);
  }
}

const passed = rows.filter((r) => r.pass).length;
console.log(`${CHECK ? "check" : "build"}: ${base.size} tokens, ${zhPaths.length} zh overrides, contrast ${passed}/${rows.length} pairs pass`);
if (problems.length) fail();
console.log(CHECK ? "check: all outputs current, all rules pass" : `build: wrote ${Object.keys(outputs).length} files`);

function fail() {
  console.error(problems.map((p) => `  ✗ ${p}`).join("\n"));
  process.exit(1);
}
